name: Trigger auto deployment for hassio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'ghcr.io/home-assistant/home-assistant:stable/**'
    - '.github/workflows/hassio-AutoDeployTrigger-25b4e420-ad23-418d-a78f-f847a299a925.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.HASSIO_REGISTRY_USERNAME }}
          password: ${{ secrets.HASSIO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sekr@netcompany.com/hassio:${{ github.sha }}
          file: ghcr.io/home-assistant/home-assistant:stable/Dockerfile
          context: ghcr.io/home-assistant/home-assistant:stable/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HASSIO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hassio -g skr-homeautomation --server docker.io --username  ${{ secrets.HASSIO_REGISTRY_USERNAME }} --password ${{ secrets.HASSIO_REGISTRY_PASSWORD }}
            az containerapp update -n hassio -g skr-homeautomation --image sekr@netcompany.com/hassio:${{ github.sha }}
